version: '3.7'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n_instance
    ports:
      - "5678:5678"
    volumes:
      - ./data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=securepassword123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_ENV=production
      - AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
      - TODOIST_API_TOKEN=${TODOIST_API_TOKEN}
